server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/work_pc
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      jdbc-url: ${DB_URL:jdbc:postgresql://localhost:5432/work_pc}
      username: ${DB_LOGIN:postgres}
      password: ${DB_PASSWORD:root}
      schema: medical_schema

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: db/changelog.xml
    enabled: ${LIQUIBASE_ENABLE:true}
    default-schema: medical_schema

  messages:
    basename: validation

  main:
    allow-circular-references: true

mybatis:
  configuration:
    autoMappingUnknownColumnBehavior: warning
    map-underscore-to-camel-case: true
